//mock数据模拟
import Mock from 'mockjs'
//图表数据
let List = []
export default{
    getStatisticalData: ()=> {
        for(let i=0;i<7;i++)
        {
            List.push(
                Mock.mock({
                    小王子:Mock.Random.float(100,8000,0,0),
                    哈:Mock.Random.float(100,8000,0,0),
                    简爱:Mock.Random.float(100,8000,0,0),
                    人生:Mock.Random.float(100,8000,0,0),
                    兄弟:Mock.Random.float(100,8000,0,0),
                    四世同堂:Mock.Random.float(100,8000,0,0),
                })
            )
        }
        return {
            code:20000,
            data:{
                //饼图
                videoData:[
                    {
                        name:'小王子',
                        value:2999
                    },
                    {
                        name:'简爱',
                        value:5999
                    },
                    {
                        name:'人生',
                        value:1500
                    },
                    {
                        name:'兄弟',
                        value:1999
                    },
                    {
                        name:'哈',
                        value:2200
                    },
                    {
                        name:'四世同堂',
                        value:4500
                    }
                ],

                //柱状图
                userData:[
                    {
                        date:'周一',
                        new:5,
                        active:200
                    },
                    {
                        date:'周二',
                        new:10,
                        active:500
                    },
                    {
                        date:'周三',
                        new:12,
                        active:550
                    },
                    {
                        date:'周四',
                        new:60,
                        active:800
                    },
                    {
                        date:'周五',
                        new:12,
                        active:550
                    },
                    {
                        date:'周六',
                        new:12,
                        active:550
                    },
                    {
                        date:'周日',
                        new:33,
                        active:170
                    },
                ],

                //折线图
               orderData:{
                    date:['20191001','20191002','20191003','20191004','20191005','20191006','20191007'],
                    data:List
                },
                tableData: [
                    {
                        name:'小王子',
                        todayBuy:50,
                        monthBuy:350,
                        totalBuy:2200
                    },
                    {
                        name:'四世同堂',
                        todayBuy:30,
                        monthBuy:220,
                        totalBuy:2400
                    },
                    {
                        name:'简爱',
                        todayBuy:80,
                        monthBuy:450,
                        totalBuy:6500
                    },
                    {
                        name:'哈',
                        todayBuy:120,
                        monthBuy:650,
                        totalBuy:4500
                    },
                    {
                        name:'人生',
                        todayBuy:30,
                        monthBuy:200,
                        totalBuy:3400
                    },
                    {
                        name:'兄弟',
                        todayBuy:35,
                        monthBuy:300,
                        totalBuy:2200
                    },
                ]
            }
        }
    }
}